# Pipeline to create RWTH gitlab pages for ImageRefiner documentation
image: python:3.7-alpine

build the car: 
  script: 
    - mkdir build
    - cd build
    - touch car.txt
    - echo "chassis" > car.txt
    - echo "engine" > car.txt
    - echo "wheels" > car.txt


