clc
close
clear

channels = {'CH1', 'CH2', 'CH3', 'CH4'};
for index = 1:length(channels)
    imageRefinerTask = Tasks.ImageRefinerTask('C:\git\imageRefinerVerification',...
        'ExportDirectory', 'C:\git\imagerefiner\target',...
        'ColumnsToExport', {'Area', 'Perimeter', 'MinFeretDiameter'},...
        'ExportFormat', 'all',...
        'VerificationMode', false,...
        'ColorChannel', channels{index},...
        'AreaBounds', [0, 100],...
        'ScalePixelToMicrometer', 0.5,...
        'ImageExtension', '.tif',...
        'Connectivity', 8,...
        'PixelSizeOfArtifacts', 15,...
        'ThresholdBlackWhiteImage', 60)
    imageRefinerTask.execute();
end