clc
close
clear

for index = 10:10:60
    imageRefinerTask = Tasks.ImageRefinerTask('C:\git\imageRefinerVerification',...
        'ExportDirectory', 'C:\git\imagerefiner\target',...
        'ColumnsToExport', {'Area', 'Perimeter', 'MinFeretDiameter'},...
        'ExportFormat', 'all',...
        'VerificationMode', false,...
        'AreaBounds', [0, 100],...
        'ScalePixelToMicrometer', 0.5,...
        'ImageExtension', '.tif',...
        'Connectivity', 8,...
        'PixelSizeOfArtifacts', 15,...
        'ThresholdBlackWhiteImage', index)
    imageRefinerTask.execute();
end